adds an output for the health check self_links to be consumed by load balancer resources outside this module
terraform-google-modules/terraform-google-vm pull request #119
Opened 2020-11-02 20:42 UTC by brandonjbjelland

## What is this change?

This change adds an output of the health_check.

## Why make this change?

Without this output, one has to conventionally construct a self-link when consumed by a `google_compute_region_backend_service`. This gives a simpler way to connect that resource with this module.

2020-11-02 20:46 UTC, bharathkkb requested changes
Thanks for the PR @brandonjbjelland 
These changes need to made in [autogen](https://github.com/terraform-google-modules/terraform-google-vm/tree/master/autogen)

2020-11-10 06:47 UTC, brandonjbjelland commented
✅  updated via the autogen file.
✅  regen modules & docs
✅  updated the CI container image version (to align w makefile and satisfy linter)

The change is working for me when called from life infra using this branch. Let me know if you need anything else to move this along.

2020-11-10 23:30 UTC, bharathkkb approved these changes
LGTM

2020-11-10 23:30 UTC, merged

2020-11-11 18:26 UTC, brandonjbjelland commented
Thanks, @bharathkkb !